General:
  Storage: flatfile
MySQL:
  host: localhost
  port: 3306
  user: root
  pass: ""
  db: minecraft
WorldGuard:
  EnableSupport: false
  ProbendingField: ProbendingField
  AutomateMatches: false
  DisableBuildOnField: true
  TeamOneZoneOne: RedZone1
  TeamOneZoneTwo: RedZone2
  TeamOneZoneThree: RedZone3
  TeamTwoZoneOne: BlueZone1
  TeamTwoZoneTwo: BlueZone2
  TeamTwoZoneThree: BlueZone3
TeamSettings:
  AllowFire: true
  AllowAir: false
  AllowWater: true
  AllowEarth: true
  AllowChi: false
  MaxTeamSize: 4
  MinTeamSize: 2
Economy:
  Enabled: false
  ServerAccount: Server
  TeamCreationFee: 350.0
  TeamRenameFee: 150.0
messages:
  Prefix: '&7[&6Probending&7] '
  noPermission: '&cYou dont have permission to do that.'
  teamAlreadyExists: '&cThat team already exists.'
  noBendingType: '&cPlayer does not have a Bending Type.'
  PlayerAlreadyInTeam: '&cThat player is already in a team.'
  ElementNotAllowed: '&c%element are not allowed to participate in Probending events.'
  TeamCreated: '&e%team &ahas been created.'
  PlayerNotInTeam: '&cYou do not have a team.'
  NotOwnerOfTeam: '&cYou dont own this team.'
  PlayerNotOnline: '&cThat player is not online.'
  MaxSizeReached: '&cThis team has reached the maximum size.'
  TeamAlreadyHasElement: '&cThis team already has this type of Bender.'
  PlayerInviteSent: '&aYou have invited &e%player &ato join &e%team.'
  PlayerInviteReceived: '&aYou have been invited to join &e%team.'
  InviteInstructions: '&aAccept this invitation using &3/pb team join %team&a.'
  TeamDoesNotExist: '&cThat team does not exist.'
  NoInviteFromTeam: '&cYou dont have an invite from that team.'
  PlayerJoinedTeam: '&e%player &ahas joined &e%team&a.'
  CantBootFromOwnTeam: '&cYou cant boot yourself from your own team.'
  PlayerNotOnThisTeam: '&cThat player is not on this team.'
  YouHaveBeenBooted: '&cYou have been booted from &3%team&c.'
  PlayerHasBeenBooted: '&e%player &chas been booted from &e%team&c.'
  YouHaveQuit: '&cYou have quit &e%team&c.'
  PlayerHasQuit: '&e%player &chas quit &e%team&c.'
  TeamDisbanded: '&e%team &chas been disbanded.'
  ArenaAlreadyExists: '&cThe arena &e%arena &calready exists.'
  ArenaCreated: '&aArena &e%arena &acreated.'
  ArenaDoesNotExist: '&cThe arena &e%arena &cdoes not exist.'
  ArenaDeleted: '&e%arena &chas been deleted.'
  SpectatorSpawnSet: '&aSet spectator spawn in &e%arena&ca.'
  fieldSpawnSet: '&aSet field spawn in &e%arena&a.'
  SentToArena: '&aSent to &e%arena&a.'
  configReloaded: '&aConfiguration reloaded.'
  RemovedFromTeamBecauseDifferentElement: '&cYou have been removed from your team because your element has changed.'
  NotEnoughMoney: '&cYou do not have the &e%amount %currency &crequired to do that.'
  MoneyWithdrawn: '&e%amount %currency &awithdrawn from your account.'
  NameTooLong: '&cTeam names cant be more than 15 characters long.'
  TeamRenamed: '&aYour team has been renamed to &e%newname&a.'
  TeamAlreadyNamedThat: '&aYour team is already named &e%newname&a.'
  ChatEnabled: '&aYou have enabled Probending Chat. To disable it, run the command again.'
  ChatDisabled: '&cYou have disabled Probending Chat.'
  OneMinuteRemaining: '&cThere is one minute remaining in this round.'
  RoundComplete: '&cThis round is now complete.'
  ClockAlreadyRunning: '&cThe clock is already running.'
  RoundStarted: '&cA probending round has been started for %seconds seconds.'
  ClockPaused: '&cThe clock has been paused with &3%seconds seconds &cleft.'
  ClockNotRunning: '&cThe clock is currently not running.'
  ClockResumed: '&cThe clock has been resumed with &3%seconds seconds &cleft.'
  ClockNotPaused: '&cThe clock is not paused.'
  ClockStopped: '&cThe clock has been stopped.'
  NoTeamPermissions: '&cYou dont have permission for any team commands.'
  NoClockPermissions: '&cYou dont have permission for any clock commands.'
  NoArenaPermissions: '&cYou dont have permission for any arena commands.'
  InvalidSign: '&cThat is not a valid Probending sign.'
  TeamSignCreated: '&cCreated a team sign for the %color team'
  SetTeamColor: '&cYour team color has been set to %color.'
  WinAddedToTeam: '&aAdded one win to &3%team&a.'
  LossAddedToTeam: '&aAdded one loss to &3%team&a.'
  match:
    MatchAlreadyGoing: '&cThere is already a match going.'
    InvalidTeamSize: '&cThe size of the team is invalid.'
    MatchStarted: '&cA match has been started between &e%team1 &cand &e%team2&c.'
    MatchStopped: '&cThe ongoing match has been stopped.'
    NoOngoingMatch: '&cThere is no ongoing match.'
    PlayerEliminated: '&4&l%player &r&chas been eliminated.'
    PlayerFouled: '&4&lFOUL: &r&e%player &cmust move back one zone.'
    MatchEnded: '&cThis probending match has ended.'
    TeamWon: '&e%team &chas won this match.'
    MoveUpOneZone: '&aYou may move up one zone.'