name: Probending
author: ProjectKorra
version: 1.1.0 - BETA PRIVATE BUILD
main: com.projectkorra.probending.Probending
depend: [ProjectKorra]
softdepend: [Vault, WorldGuard]
commands:
  probending:
    aliases: [pb]
permissions:
  probending.admin:
    default: false
    children:
      probending.command.team.create: true
      probending.command.team.invite: true
      probending.command.team.info: true
      probending.command.team.join: true
      probending.command.team.kick: true
      probending.command.team.quit: true
      probending.command.team.disband: true
      probending.command.team.disband.other: true
      probending.command.team.list: true
      probending.command.reload: true
      probending.command.team.rename: true
      probending.command.chat: true
      probending.command.team.addwin: true
      probending.command.team.addloss: true
      probending.command.round.start: true
      probending.command.round.stop: true
      probending.command.round.resume: true
      probending.command.round.pause: true
      probending.command.arnea.create: true
      probending.worldguard.buildonfield: true
      probending.command.setspawn: true
  probending.user:
    default: false
    children:
      probending.command.team.create: true
      probending.command.team.invite: true
      probending.command.team.info: true
      probending.command.team.join: true
      probending.command.team.kick: true
      probending.command.team.quit: true
      probending.command.team.list: true
      probending.command.team.rename: true
      probending.command.team.disband: true
      probending.command.chat: true