name: Probending
author: ProjectKorra
version: 1.0.0
main: com.projectkorra.probending.Probending
depend: [ProjectKorra]
softdepend: [Vault, WorldGuard]
commands:
  probending:
    aliases: [pb]
permissions:
  probending.admin:
    default: false
    children:
      probending.team.create: true
      probending.team.invite: true
      probending.team.info: true
      probending.team.join: true
      probending.team.kick: true
      probending.team.quit: true
      probending.team.disband: true
      probending.team.disband.other: true
      probending.team.list: true
      probending.reload: true
      probending.team.rename: true
      probending.chat: true
      probending.team.addwin: true
      probending.team.addloss: true
      probending.round.start: true
      probending.round.stop: true
      probending.round.resume: true
      probending.round.pause: true
      probending.worldguard.buildonfield: true
      probending.setspawn: true
  probending.user:
    default: false
    children:
      probending.team.create: true
      probending.team.invite: true
      probending.team.info: true
      probending.team.join: true
      probending.team.kick: true
      probending.team.quit: true
      probending.team.list: true
      probending.team.rename: true
      probending.chat: true
      probending.challenge.accept: true
      probending.challenge: true